name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v2
        env: 
          REACT_APP_API_URI: ${{ secrets.REACT_APP_API_URI }}
        with:
          build: yarn build
          start: yarn cypress